name: rutea

services:

  rutea-db:
    image: mariadb:11.3.2
    container_name: rutea-db
    env_file: .env
    environment:
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${RUTEA_DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 20s
    # volumes:
    #   - rutea-db-data:/var/lib/mysql

# volumes:
#   rutea-db-data:
