openapi: 3.0.1
info:
  title: Rutea API - Rutas y Puntos de Interés
  description: API REST para la gestión de rutas turísticas, puntos de interés, usuarios y reseñas.
  version: v1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor Local de Desarrollo

paths:
  # --------------------------------------------------------------------------------
  # RUTAS DE USUARIO
  # --------------------------------------------------------------------------------
  /api/usuarios:
    get:
      tags: [usuario-controller]
      summary: Lista todos los usuarios o filtra por experiencia y premium
      parameters:
        - name: experiencia
          in: query
          required: false
          schema: {type: integer}
        - name: premium
          in: query
          required: false
          schema: {type: boolean}
      responses:
        '200': {description: Lista de usuarios, content: {application/json: {schema: {type: array, items: {$ref: '#/components/schemas/Usuario'}}}}}
        '500': {$ref: '#/components/responses/InternalError'}
    post:
      tags: [usuario-controller]
      summary: Crea un nuevo usuario
      requestBody: {required: true, content: {application/json: {schema: {$ref: '#/components/schemas/Usuario'}}}}
      responses:
        '201': {description: Usuario creado con éxito., content: {application/json: {schema: {$ref: '#/components/schemas/Usuario'}}}}
        '400': {$ref: '#/components/responses/BadRequestError'}
        '500': {$ref: '#/components/responses/InternalError'}

  /api/usuarios/{id}:
    get:
      tags: [usuario-controller]
      summary: Obtiene un usuario por ID
      parameters: [{name: id, in: path, required: true, schema: {type: integer, format: int64}}]
      responses:
        '200': {description: Usuario encontrado., content: {application/json: {schema: {$ref: '#/components/schemas/Usuario'}}}}
        '404': {$ref: '#/components/responses/NotFoundError'}
        '500': {$ref: '#/components/responses/InternalError'}
    put:
      tags: [usuario-controller]
      summary: Modifica un usuario existente por ID
      parameters: [{name: id, in: path, required: true, schema: {type: integer, format: int64}}]
      requestBody: {required: true, content: {application/json: {schema: {$ref: '#/components/schemas/Usuario'}}}}
      responses:
        '200': {description: Usuario modificado con éxito., content: {application/json: {schema: {$ref: '#/components/schemas/Usuario'}}}}
        '400': {$ref: '#/components/responses/BadRequestError'}
        '404': {$ref: '#/components/responses/NotFoundError'}
        '500': {$ref: '#/components/responses/InternalError'}
    delete:
      tags: [usuario-controller]
      summary: Elimina un usuario por ID
      parameters: [{name: id, in: path, required: true, schema: {type: integer, format: int64}}]
      responses:
        '204': {description: Usuario eliminado con éxito.}
        '404': {$ref: '#/components/responses/NotFoundError'}
        '500': {$ref: '#/components/responses/InternalError'}

  # --------------------------------------------------------------------------------
  # RUTAS DE CATEGORIAS
  # --------------------------------------------------------------------------------
  /api/categorias:
    get:
      tags: [categoria-controller]
      summary: Lista todas las categorías con filtrado opcional
      parameters:
        - name: activa
          in: query
          required: false
          schema: {type: boolean}
        - name: costeMax
          in: query
          required: false
          schema: {type: number, format: float}
      responses:
        '200': {description: Lista de categorías, content: {application/json: {schema: {type: array, items: {$ref: '#/components/schemas/Categoria'}}}}}
        '500': {$ref: '#/components/responses/InternalError'}
    post:
      tags: [categoria-controller]
      summary: Crea una nueva categoría
      requestBody: {required: true, content: {application/json: {schema: {$ref: '#/components/schemas/Categoria'}}}}
      responses:
        '201': {description: Categoría creada con éxito.}
        '400': {$ref: '#/components/responses/BadRequestError'}
        '500': {$ref: '#/components/responses/InternalError'}

  /api/categorias/{id}:
    get:
      tags: [categoria-controller]
      summary: Obtiene una categoría por ID
      parameters: [{name: id, in: path, required: true, schema: {type: integer, format: int64}}]
      responses:
        '200': {description: Categoría encontrada.}
        '404': {$ref: '#/components/responses/NotFoundError'}
        '500': {$ref: '#/components/responses/InternalError'}
    put:
      tags: [categoria-controller]
      summary: Modifica una categoría existente por ID
      parameters: [{name: id, in: path, required: true, schema: {type: integer, format: int64}}]
      requestBody: {required: true, content: {application/json: {schema: {$ref: '#/components/schemas/Categoria'}}}}
      responses:
        '200': {description: Categoría modificada con éxito.}
        '400': {$ref: '#/components/responses/BadRequestError'}
        '404': {$ref: '#/components/responses/NotFoundError'}
        '500': {$ref: '#/components/responses/InternalError'}
    delete:
      tags: [categoria-controller]
      summary: Elimina una categoría por ID
      parameters: [{name: id, in: path, required: true, schema: {type: integer, format: int64}}]
      responses:
        '204': {description: Categoría eliminada con éxito.}
        '404': {$ref: '#/components/responses/NotFoundError'}
        '500': {$ref: '#/components/responses/InternalError'}

  # --------------------------------------------------------------------------------
  # RUTAS DE PUNTOS DE INTERES
  # --------------------------------------------------------------------------------
  /api/puntos:
    get:
      tags: [punto-interes-controller]
      summary: Lista todos los puntos de interés con filtrado opcional
      parameters:
        - name: abierto
          in: query
          required: false
          schema: {type: boolean}
        - name: minPuntuacion
          in: query
          required: false
          schema: {type: number, format: float}
      responses:
        '200': {description: Lista de puntos, content: {application/json: {schema: {type: array, items: {$ref: '#/components/schemas/PuntoInteres'}}}}}
        '500': {$ref: '#/components/responses/InternalError'}
    post:
      tags: [punto-interes-controller]
      summary: Crea un nuevo punto de interés
      requestBody: {required: true, content: {application/json: {schema: {$ref: '#/components/schemas/PuntoInteres'}}}}
      responses:
        '201': {description: Punto creado con éxito.}
        '400': {$ref: '#/components/responses/BadRequestError'}
        '500': {$ref: '#/components/responses/InternalError'}

  /api/puntos/{id}:
    get:
      tags: [punto-interes-controller]
      summary: Obtiene un punto de interés por ID
      parameters: [{name: id, in: path, required: true, schema: {type: integer, format: int64}}]
      responses:
        '200': {description: Punto encontrado.}
        '404': {$ref: '#/components/responses/NotFoundError'}
        '500': {$ref: '#/components/responses/InternalError'}
    put:
      tags: [punto-interes-controller]
      summary: Modifica un punto de interés existente por ID
      parameters: [{name: id, in: path, required: true, schema: {type: integer, format: int64}}]
      requestBody: {required: true, content: {application/json: {schema: {$ref: '#/components/schemas/PuntoInteres'}}}}
      responses:
        '200': {description: Punto modificado con éxito.}
        '400': {$ref: '#/components/responses/BadRequestError'}
        '404': {$ref: '#/components/responses/NotFoundError'}
        '500': {$ref: '#/components/responses/InternalError'}
    delete:
      tags: [punto-interes-controller]
      summary: Elimina un punto de interés por ID
      parameters: [{name: id, in: path, required: true, schema: {type: integer, format: int64}}]
      responses:
        '204': {description: Punto eliminado con éxito.}
        '404': {$ref: '#/components/responses/NotFoundError'}
        '500': {$ref: '#/components/responses/InternalError'}

  # --------------------------------------------------------------------------------
  # RUTAS DE RUTAS
  # --------------------------------------------------------------------------------
  /api/rutas:
    get:
      tags: [ruta-controller]
      summary: Lista todas las rutas con filtrado opcional
      parameters:
        - name: dificultad
          in: query
          required: false
          schema: {type: string}
      responses:
        '200': {description: Lista de rutas, content: {application/json: {schema: {type: array, items: {$ref: '#/components/schemas/Ruta'}}}}}
        '500': {$ref: '#/components/responses/InternalError'}
    post:
      tags: [ruta-controller]
      summary: Crea una nueva ruta
      requestBody: {required: true, content: {application/json: {schema: {$ref: '#/components/schemas/Ruta'}}}}
      responses:
        '201': {description: Ruta creada con éxito.}
        '400': {$ref: '#/components/responses/BadRequestError'}
        '500': {$ref: '#/components/responses/InternalError'}

  /api/rutas/{id}:
    get:
      tags: [ruta-controller]
      summary: Obtiene una ruta por ID
      parameters: [{name: id, in: path, required: true, schema: {type: integer, format: int64}}]
      responses:
        '200': {description: Ruta encontrada.}
        '404': {$ref: '#/components/responses/NotFoundError'}
        '500': {$ref: '#/components/responses/InternalError'}
    put:
      tags: [ruta-controller]
      summary: Modifica una ruta existente por ID
      parameters: [{name: id, in: path, required: true, schema: {type: integer, format: int64}}]
      requestBody: {required: true, content: {application/json: {schema: {$ref: '#/components/schemas/Ruta'}}}}
      responses:
        '200': {description: Ruta modificada con éxito.}
        '400': {$ref: '#/components/responses/BadRequestError'}
        '404': {$ref: '#/components/responses/NotFoundError'}
        '500': {$ref: '#/components/responses/InternalError'}
    delete:
      tags: [ruta-controller]
      summary: Elimina una ruta por ID
      parameters: [{name: id, in: path, required: true, schema: {type: integer, format: int64}}]
      responses:
        '204': {description: Ruta eliminada con éxito.}
        '404': {$ref: '#/components/responses/NotFoundError'}
        '500': {$ref: '#/components/responses/InternalError'}

  # --------------------------------------------------------------------------------
  # RUTAS DE RESEÑAS
  # --------------------------------------------------------------------------------
  /api/resenas:
    get:
      tags: [resena-controller]
      summary: Lista todas las reseñas con filtrado opcional
      parameters:
        - name: valoracion
          in: query
          required: false
          schema: {type: integer, format: int32}
      responses:
        '200': {description: Lista de reseñas, content: {application/json: {schema: {type: array, items: {$ref: '#/components/schemas/Resena'}}}}}
        '500': {$ref: '#/components/responses/InternalError'}
    post:
      tags: [resena-controller]
      summary: Crea una nueva reseña
      requestBody: {required: true, content: {application/json: {schema: {$ref: '#/components/schemas/Resena'}}}}
      responses:
        '201': {description: Reseña creada con éxito.}
        '400': {$ref: '#/components/responses/BadRequestError'}
        '500': {$ref: '#/components/responses/InternalError'}

  /api/resenas/{id}:
    get:
      tags: [resena-controller]
      summary: Obtiene una reseña por ID
      parameters: [{name: id, in: path, required: true, schema: {type: integer, format: int64}}]
      responses:
        '200': {description: Reseña encontrada.}
        '404': {$ref: '#/components/responses/NotFoundError'}
        '500': {$ref: '#/components/responses/InternalError'}
    put:
      tags: [resena-controller]
      summary: Modifica una reseña existente por ID
      parameters: [{name: id, in: path, required: true, schema: {type: integer, format: int64}}]
      requestBody: {required: true, content: {application/json: {schema: {$ref: '#/components/schemas/Resena'}}}}
      responses:
        '200': {description: Reseña modificada con éxito.}
        '400': {$ref: '#/components/responses/BadRequestError'}
        '404': {$ref: '#/components/responses/NotFoundError'}
        '500': {$ref: '#/components/responses/InternalError'}
    delete:
      tags: [resena-controller]
      summary: Elimina una reseña por ID
      parameters: [{name: id, in: path, required: true, schema: {type: integer, format: int64}}]
      responses:
        '204': {description: Reseña eliminada con éxito.}
        '404': {$ref: '#/components/responses/NotFoundError'}
        '500': {$ref: '#/components/responses/InternalError'}

components:
  schemas:
    # --------------------------------------------------------------------------------
    # DEFINICIÓN DE ESQUEMAS DE ERROR
    # --------------------------------------------------------------------------------
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

    ValidationErrorResponse:
      type: object
      additionalProperties:
        type: string

    # --------------------------------------------------------------------------------
    # ESQUEMAS DEL MODELO
    # --------------------------------------------------------------------------------
    Usuario:
      required: [email, fechaRegistro, password, username]
      type: object
      properties:
        id: {type: integer, format: int64}
        username: {type: string, minLength: 4}
        email: {type: string}
        password: {type: string}
        nivelExperiencia: {type: integer, format: int32, minimum: 0}
        esPremium: {type: boolean}
        fechaRegistro: {type: string, format: date}
    Ruta:
      required: [fechaRealizacion, titulo]
      type: object
      properties:
        id: {type: integer, format: int64}
        titulo: {type: string}
        dificultad: {type: string}
        distanciaKm: {type: number, format: float}
        duracionMinutos: {type: integer, format: int32}
        publica: {type: boolean}
        fechaRealizacion: {type: string, format: date}
        creador: {$ref: '#/components/schemas/Usuario'}
        puntosInteres: {type: array, items: {$ref: '#/components/schemas/PuntoInteres'}}
    PuntoInteres:
      required: [latitud, longitud, nombre]
      type: object
      properties:
        id: {type: integer, format: int64}
        nombre: {type: string}
        latitud: {type: number, format: double}
        longitud: {type: number, format: double}
        puntuacionMedia: {type: number, format: float, minimum: 0, maximum: 5}
        abiertoActualmente: {type: boolean}
        fechaCreacion: {type: string, format: date-time}
        categoria: {$ref: '#/components/schemas/Categoria'}
    Categoria:
      required: [nombre]
      type: object
      properties:
        id: {type: integer, format: int64}
        nombre: {type: string}
        descripcion: {type: string}
        iconoUrl: {type: string}
        ordenPrioridad: {type: integer, format: int32}
        activa: {type: boolean}
        costePromedio: {type: number, format: float}
    Resena:
      required: [comentario, valoracion]
      type: object
      properties:
        id: {type: integer, format: int64}
        titulo: {type: string}
        comentario: {type: string, minLength: 10}
        valoracion: {type: integer, format: int32, minimum: 1, maximum: 5}
        likes: {type: integer, format: int32}
        editada: {type: boolean}
        fechaPublicacion: {type: string, format: date}
        usuario: {$ref: '#/components/schemas/Usuario'}
        puntoInteres: {$ref: '#/components/schemas/PuntoInteres'}

  responses:
    # --------------------------------------------------------------------------------
    # RESPUESTAS REUTILIZABLES DE ERROR
    # --------------------------------------------------------------------------------
    NotFoundError:
      description: Recurso no encontrado (404 NOT FOUND).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: "404"
            message: "Recurso no encontrado con ID: 99"

    BadRequestError:
      description: La petición contiene datos inválidos o faltantes (400 BAD REQUEST).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationErrorResponse'

    InternalError:
      description: Error interno del servidor (500 INTERNAL SERVER ERROR).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: "500"
            message: "Ha ocurrido un error interno en el servidor. Por favor, inténtelo más tarde."