spring.datasource.url=jdbc:mariadb://rutea-db:3306/${MARIADB_DATABASE}
spring.datasource.username=${MARIADB_USER}
spring.datasource.password=${RUTEA_DATABASE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
